apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: hacbs-test-project-or0i
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hacbs-test-project-or0i
    app.kubernetes.io/part-of: rhtap-demo-app
  name: hacbs-test-project-or0i
spec:
  replicas: 0
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: hacbs-jvm-build-test-project
      app.kubernetes.io/instance: hacbs-test-project-or0i
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hacbs-jvm-build-test-project
        app.kubernetes.io/instance: hacbs-test-project-or0i
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-shqp-tenant/rhtap-demo-app/hacbs-test-project-or0i@sha256:a3d7053c661b7256237bdeb45da3da53c3a8290613876d270ca49c6486f03e0d
        name: hacbs-jvm-build-test-project
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
